name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set_up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies in python virtual environmnet and run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r 2_GithubActionPipeline/requirements.txt
          pytest 2_GithubActionPipeline/test_app.py
        shell: bash

  deploy_staging:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{secrets.EC2_IP}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_SSH}}
          source: "2_GithubActionPipeline/*"
          target: ${{secrets.EC2_PATH}}

  
          

      
